/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package FormulariosInternos;

import Objetos.dbConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arce
 */
public class JiFrmDiasFaltantes extends javax.swing.JInternalFrame {

    /**
     * Creates new form JiFrmDiasFaltantes
     */
    dbConnection conexion;

    public JiFrmDiasFaltantes() {
        initComponents();
        conexion = new dbConnection();
        txtCedula.setText("");
        verMiembros();
    }

    public void diasRestantes() {
        try (Connection con = DriverManager.getConnection(conexion.getUrl(),
                conexion.getUsername(), conexion.getPassword())) {

            int cedula = Integer.parseInt(txtCedula.getText());
            DefaultTableModel modelo = new DefaultTableModel();
            PreparedStatement pstmn = con.prepareCall("call verDiasRestantes(?)");
            pstmn.setInt(1, cedula);

            ResultSet rs = pstmn.executeQuery();
            ResultSetMetaData rsmt = rs.getMetaData();

            for (int i = 1; i <= rsmt.getColumnCount(); i++) {
                modelo.addColumn(rsmt.getColumnLabel(i));
            }

            while (rs.next()) {
                Object[] filas = new Object[rsmt.getColumnCount()];
                for (int i = 1; i <= rsmt.getColumnCount(); i++) {
                    filas[i - 1] = rs.getObject(i);
                }
                modelo.addRow(filas);
            }
            tableDiasRestantes.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }

    public void verMiembros() {
        try (Connection con = DriverManager.getConnection(conexion.getUrl(),
                conexion.getUsername(), conexion.getPassword())) {

            DefaultTableModel modelo = new DefaultTableModel();
            PreparedStatement pstmn = con.prepareCall("call verMiembro()");

            ResultSet rs = pstmn.executeQuery();
            ResultSetMetaData rsmt = rs.getMetaData();

            for (int i = 1; i <= rsmt.getColumnCount(); i++) {
                modelo.addColumn(rsmt.getColumnLabel(i));
            }

            while (rs.next()) {
                Object[] filas = new Object[rsmt.getColumnCount()];
                for (int i = 1; i <= rsmt.getColumnCount(); i++) {
                    filas[i - 1] = rs.getObject(i);
                }
                modelo.addRow(filas);
            }
            tableDiasRestantes.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDiasRestantes = new javax.swing.JTable();
        txtCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tableDiasRestantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDiasRestantes);

        txtCedula.setText("jTextField1");

        jLabel1.setText("Escriba la cedula:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try{
            diasRestantes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar una cedula");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDiasRestantes;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
