/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package FormulariosInternos;

import Objetos.Cliente;
import Objetos.Estado;
import Objetos.dbConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xdand
 */
public class JiFrmEstadoMembresia extends javax.swing.JInternalFrame {

    /**
     * Creates new form JiFrmEstadoMembresia
     */
    dbConnection conexion;
    ArrayList<String> estados;
    String[] encabezado={"ID","Cedula","Nombre","Estado"};
    ArrayList<Cliente> registros;
    public JiFrmEstadoMembresia(ArrayList<Cliente> registros) {
        initComponents();
        conexion=new dbConnection();
        this.registros=registros;
        estados=new ArrayList();
        estados.add("ACTIVO");
        estados.add("INACTIVO");
        llenarCombo();
        MostrarMiembro();
        
    }
    public void llenarCombo()
    {
        comboEstados.removeAllItems();
        comboEstados.addItem("Seleccione un miembro");
        for (int i = 0; i < estados.size(); i++) {
            comboEstados.addItem(estados.get(i));
        }
    }
    public void filtrar(){
        try(Connection con = DriverManager.getConnection(conexion.getUrl(),
                conexion.getUsername(), conexion.getPassword())){
            
            DefaultTableModel modelo = new DefaultTableModel();
            
            PreparedStatement pstmn = con.prepareCall("call Estados(?)");
            pstmn.setString(1, estados.get(comboEstados.getSelectedIndex()-1));
            
            ResultSet rs = pstmn.executeQuery();
            ResultSetMetaData rsmt = rs.getMetaData();
            
            for(int i = 1; i<=rsmt.getColumnCount(); i++){
                modelo.addColumn(rsmt.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object[] filas = new Object[rsmt.getColumnCount()];
                for(int i = 1; i<=rsmt.getColumnCount(); i++){
                    filas[i-1] = rs.getObject(i);
                }
                modelo.addRow(filas);
            }
            tableEstado.setModel(modelo);
            
            
    }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }
    
    public void MostrarMiembro(){
        try(Connection con = DriverManager.getConnection(conexion.getUrl(),conexion.getUsername(), conexion.getPassword()))
        {

            DefaultTableModel modelo = new DefaultTableModel();
            Statement stm = con.createStatement();
            String query = "call MostrarMiembros()";
            ResultSet rs = stm.executeQuery(query);
            ResultSetMetaData rsmt = rs.getMetaData();
    
            for(int i = 1; i<=rsmt.getColumnCount(); i++){
                modelo.addColumn(rsmt.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object[] filas = new Object[rsmt.getColumnCount()];
                for(int i = 1; i<=rsmt.getColumnCount(); i++){
                    filas[i-1] = rs.getObject(i);
                }
                modelo.addRow(filas);
            }
            tableEstado.setModel(modelo);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
        
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        comboEstados = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEstado = new javax.swing.JTable();

        jCheckBox1.setText("jCheckBox1");

        setClosable(true);
        setIconifiable(true);

        comboEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Estado de la membresia:");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        tableEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableEstado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(comboEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        if(comboEstados.getSelectedIndex()>0)
        {
            filtrar();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Selecione un estado");
        }
       
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboEstados;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEstado;
    // End of variables declaration//GEN-END:variables
}
