/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormulariosPrincipales;

import FormulariosInternos.JiFrmRegistrarAsistencia;
import FormulariosInternos.JiFrmEstadoMembresia;
import FormulariosInternos.JiFrmPeriodosPagos;
import FormulariosInternos.JiFrmRegistrarMembresia;
import FormulariosInternos.JiFrmRegistrarPago;
import FormulariosInternos.JiFrmRegistro;
import FormulariosInternos.JiFrmReportesAsistencias;
import FormulariosInternos.JiFrmReportesMembresias;
import Objetos.Asistencia;
import Objetos.Estado;
import Objetos.Membresia;
import Objetos.Cliente;
import Objetos.dbConnection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xdand
 */

public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    
    private ArrayList<Cliente> registros = new ArrayList();
    public frmPrincipal(int idUser, int profile) {
        initComponents();
        
        if (profile != 1){
            menuReportes.disable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        principalDesktop = new javax.swing.JDesktopPane();
        menuRegistro = new javax.swing.JMenuBar();
        menuRegistros = new javax.swing.JMenu();
        menuMiembros = new javax.swing.JMenuItem();
        menuAsistencia = new javax.swing.JMenuItem();
        menuPago = new javax.swing.JMenuItem();
        menuRegistrarMembresia = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuEstado = new javax.swing.JMenuItem();
        menuRasistencias = new javax.swing.JMenuItem();
        menuTipoMembresia = new javax.swing.JMenuItem();
        jMenuPeriodoPagos = new javax.swing.JMenuItem();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout principalDesktopLayout = new javax.swing.GroupLayout(principalDesktop);
        principalDesktop.setLayout(principalDesktopLayout);
        principalDesktopLayout.setHorizontalGroup(
            principalDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        principalDesktopLayout.setVerticalGroup(
            principalDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        menuRegistros.setText("Registros");

        menuMiembros.setText("Registrar Miembro");
        menuMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMiembrosActionPerformed(evt);
            }
        });
        menuRegistros.add(menuMiembros);

        menuAsistencia.setText("Registrar Asistencia");
        menuAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAsistenciaActionPerformed(evt);
            }
        });
        menuRegistros.add(menuAsistencia);

        menuPago.setText("Registrar Pago");
        menuPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagoActionPerformed(evt);
            }
        });
        menuRegistros.add(menuPago);

        menuRegistrarMembresia.setText("Registrar Membresia");
        menuRegistrarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarMembresiaActionPerformed(evt);
            }
        });
        menuRegistros.add(menuRegistrarMembresia);

        menuRegistro.add(menuRegistros);

        menuReportes.setText("Reportes");

        menuEstado.setText("Activo/Inactivo");
        menuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstadoActionPerformed(evt);
            }
        });
        menuReportes.add(menuEstado);

        menuRasistencias.setText("Reporte de asistencias");
        menuRasistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRasistenciasActionPerformed(evt);
            }
        });
        menuReportes.add(menuRasistencias);

        menuTipoMembresia.setText("Tipo de membresias");
        menuTipoMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTipoMembresiaActionPerformed(evt);
            }
        });
        menuReportes.add(menuTipoMembresia);

        jMenuPeriodoPagos.setText("Periodo de pagos");
        jMenuPeriodoPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPeriodoPagosActionPerformed(evt);
            }
        });
        menuReportes.add(jMenuPeriodoPagos);

        menuRegistro.add(menuReportes);

        setJMenuBar(menuRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstadoActionPerformed
        // TODO add your handling code here:
        JiFrmEstadoMembresia estado =new JiFrmEstadoMembresia(registros);
        principalDesktop.add(estado);
        estado.show();
    }//GEN-LAST:event_menuEstadoActionPerformed

    private void menuMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMiembrosActionPerformed
        // TODO add your handling code here:
        JiFrmRegistro registro=new JiFrmRegistro(registros);
        principalDesktop.add(registro);
        registro.show();
    }//GEN-LAST:event_menuMiembrosActionPerformed

    private void menuPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagoActionPerformed
        // TODO add your handling code here:
        JiFrmRegistrarPago pago =new JiFrmRegistrarPago(registros);
        principalDesktop.add(pago);
        pago.show();
        
    }//GEN-LAST:event_menuPagoActionPerformed

    private void menuAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAsistenciaActionPerformed
        // TODO add your handling code here:
        JiFrmRegistrarAsistencia asistencia =new JiFrmRegistrarAsistencia(registros);
        principalDesktop.add(asistencia);
        asistencia.show();
    }//GEN-LAST:event_menuAsistenciaActionPerformed

    private void menuRasistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRasistenciasActionPerformed
        // TODO add your handling code here:
        JiFrmReportesAsistencias Rasistencias=new JiFrmReportesAsistencias();
        principalDesktop.add(Rasistencias);
        Rasistencias.show();
    }//GEN-LAST:event_menuRasistenciasActionPerformed

    private void menuTipoMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTipoMembresiaActionPerformed
        // TODO add your handling code here:
        JiFrmReportesMembresias membresias=new JiFrmReportesMembresias();
         principalDesktop.add(membresias);
        membresias.show();
    }//GEN-LAST:event_menuTipoMembresiaActionPerformed

    private void menuRegistrarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarMembresiaActionPerformed
        JiFrmRegistrarMembresia Rmembresia =new JiFrmRegistrarMembresia();
        principalDesktop.add(Rmembresia);
        Rmembresia.show();
    }//GEN-LAST:event_menuRegistrarMembresiaActionPerformed

    private void jMenuPeriodoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPeriodoPagosActionPerformed
        // TODO add your handling code here:
        JiFrmPeriodosPagos PeriodoPagos = new JiFrmPeriodosPagos();
        principalDesktop.add(PeriodoPagos);
        PeriodoPagos.show();
    }//GEN-LAST:event_jMenuPeriodoPagosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal(0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem jMenuPeriodoPagos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuItem menuAsistencia;
    private javax.swing.JMenuItem menuEstado;
    private javax.swing.JMenuItem menuMiembros;
    private javax.swing.JMenuItem menuPago;
    private javax.swing.JMenuItem menuRasistencias;
    private javax.swing.JMenuItem menuRegistrarMembresia;
    private javax.swing.JMenuBar menuRegistro;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem menuTipoMembresia;
    private javax.swing.JDesktopPane principalDesktop;
    // End of variables declaration//GEN-END:variables
}
